<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net6.0-windows</TargetFramework>
    <Nullable>enable</Nullable>
    <UseWPF>true</UseWPF>
    <Version>0.1.0</Version>
    <UseWindowsForms>true</UseWindowsForms>
    <ApplicationIcon>App.ico</ApplicationIcon>
  </PropertyGroup>

  <ItemGroup>
    <Content Include="App.ico" />
  </ItemGroup>

  <ItemGroup>
    <Folder Include="Views\" />
  </ItemGroup>

</Project>
